### ISSUE TITLE
Add primitve: (string->number)

### ISSUE THREAD

**Issue by mbillingr** [mbillingr/interpreter#10]
This would be similar to the (read) procedure, but utilize only the number part of the S-expression parser.

**Comment by mbillingr** [comment]
Ok, not trivially easy after all...

I'd have to factor out part of `Expression::from_literal` into maybe `Number::from_str`.
This would be an opportunity to revise parsing rationals, complex, and special numbers like inf or nan in a scheme compliant way.

**Comment by pgl10** [comment]
Please have a look at this example.
>> (define x 1)
>> (set! x (read))
3.14
Now x is a real number. This is OK.
>> (set! x (read))
2+3i
>> (symbol? x)
Now x is a symbol and it is not a complex number (neither a number).
Does this show that today (read) don't know to read a complex number ?

**Comment by mbillingr** [comment]
> Does this show that today (read) don't know to read a complex number ?

Exactly. Read can only parse integers and real numbers. Rationals and complex are not implemented.
