### ISSUE TITLE
complex number

### ISSUE THREAD

**Issue by pgl10** [mbillingr/interpreter#13]
(define x (make-rectangular 1 2))
This is new and this is OK. Congratulations.
But what about : (real-part x) and (imag-part x) ?

**Comment by mbillingr** [comment]
erm... good question. They *should* be there. I'll investigate...

**Comment by mbillingr** [comment]
Looks like they were accidentally removed in commit 40b32d126d467ed41311162bf266de0f5e27db7d that added `(string->number)`.

**Comment by mbillingr** [comment]
fixed in 66e7e1bcbf95ad962be042d0168ebb19fe4c9043 and 1a538f0a49d8143100e750a1883888d2aff798e0.
