### ISSUE TITLE
Add an (exit) procedure

### ISSUE THREAD

**Issue by mbillingr** [mbillingr/interpreter#7]
Tank you @pgl10 for suggesting an `(exit)` procedure.
The command should
1. display `Bye` .
2. wait for two seconds.
3. exit the session

**Comment by mbillingr** [comment]
I totally agree with point 3.

Currently, the only way to exit the interpreter is sending `EOF` by typing `Ctrl-D` . This is probably obvious for Linux users but may be unintuitive on Windows. Furthermore, it cannot be invoked programmatically.

I'm not sure about points 1 and 2. What is the purpose of displaying `Bye`  and waiting?

**Comment by pgl10** [comment]
Points 1) and 2) are usefull for the user. The interpreter is showing to his what is happending.

**Comment by mbillingr** [comment]
Ok, 1) would provide feedback to the user.

I'm not convinced that 2) adding a delay is such a good idea. The user can see the program output in the terminal after the interpreter stops.

**Comment by mbillingr** [comment]
I figured that on Windows the console window does not stay open when running the .exe file from explorer. In this case "Bye" and delay make sense.

However, I want to use the interpreter for scripting, which makes spurious output and delays undesirable.

Solution:
`(exit)` without arguments displays `"Bye."` and exits after a delay.
`(exit <obj>)` with an argument does not display anything and exits immediately with an exit code determined by `<obj>`.

**Comment by pgl10** [comment]
Thanks for this solution. If (exit) without "Bye" and without delay is an easier solution : this is the best choice. Of course, I agree with you and you may do as you suggest.
