### ISSUE TITLE
complex numbers

### ISSUE THREAD

**Issue by pgl10** [mbillingr/interpreter#9]
At https://www.scheme.com/tspl4/objects.html it is written that (real-part x) and (imag-part x) are the two commands to get the real part of the complex number x and its imaginary part.
Have you the purpose to do these two new native commands ? Thank you.

**Comment by mbillingr** [comment]
Thank you for reporting!
I forgot to add these commands. Complex numbers are not very useful without them...

**Comment by mbillingr** [comment]
Also the procedure to create complex numbers should be `(make-rectangular)` according to R7RS, rather than `(complex)`.

**Comment by pgl10** [comment]
If one day (sqrt x) have to work when x is a complex number, then (make-rectangular a b), (make-polar a b), (angle a) and (magnitude a) should be defined and useful. But I don't know if (sqrt x) is needed when x is a complex number. I think that x^y (exponentiation operator) is not needed neither when x and y are complex numbers. (make-rectangular) according to R7RS is largely enough.
